8/5 before start

diff --git a/OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile0.developer b/OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile0.developer
--- a/OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile0.developer
+++ b/OracleWebLogic/dockerfiles/12.2.1.3/Dockerfile0.developer
@@ -28,7 +28,7 @@
 # Extend base JRE image
 # You must build the image by using the Dockerfile in GitHub project `../../../OracleJava/java8`
 # ----------------------------------------------------------------------------------------------
-FROM dockeronwindows/ser-java0:ananth as builder
+FROM dockeronwindows/ser-java0:ananth
 USER ContainerAdministrator
 # Labels
 # ------
@@ -41,18 +41,14 @@ LABEL "provider"="Oracle"                                               `
 
 # Common environment variables required for this build (do NOT change)
 # --------------------------------------------------------------------
-ENV ORACLE_HOME=C:\u01\oracle `
-    # USER_MEM_ARGS="-Djava.security.egd=file:\dev\.\urandom" `
-    PATH=%PATH%;%JAVA_HOME%\bin;C:\u01\oracle\oracle_common\common\bin;C:\u01\oracle\wlserver\common\bin
-
+ENV ORACLE_HOME=C:\u01\oracle
+RUN setx /M PATH %JAVA_HOME%\bin;C:\u01\oracle\oracle_common\common\bin;C:\u01\oracle\wlserver\common\bin;%PATH%
+USER ContainerUser
 # Setup filesystem and oracle user
 # Adjust file permissions, go to \u01 as user 'oracle' to proceed with WLS installation
 # ------------------------------------------------------------
 RUN mkdir C:\u01\oracle
-#&&
-    # useradd -b \u01 -d \u01\oracle -m -s \bin\bash oracle && `
-    # chown oracle:root -R /u01 && `
-    # chmod -R 775 /u01
+RUN icacls "C:\u01\oracle" "/grant:r" "DefaultAccount:(OI)(CI)F" /T
 
 # Environment variables required for this build (do NOT change)
 # -------------------------------------------------------------
@@ -65,18 +61,16 @@ COPY $FMW_PKG install.file oraInst.loc C:\u01\
 
 # Install
 # ------------------------------------------------------------
-# USER ContainerUser
+USER ContainerAdministrator
 RUN cd C:\u01 && %JAVA_HOME%\bin\jar xf C:\u01\%FMW_PKG% && cd \ && `
-    %JAVA_HOME%\bin\java -jar C:\u01\%FMW_JAR% -silent -responseFile C:\u01\install.file -invPtrLoc C:\u01\oraInst.loc -jreLoc %JAVA_HOME% -ignoreSysPrereqs -force -novalidation ORACLE_HOME=%ORACLE_HOME% && `
-    DEL /Q C:\u01\%FMW_JAR% C:\u01\%FMW_PKG% C:\u01\install.file && `
-    RD /S /Q C:\u01\oracle\cfgtoollogs
+    %JAVA_HOME%\bin\java -jar C:\u01\%FMW_JAR% -silent -responseFile C:\u01\install.file -invPtrLoc C:\u01\oraInst.loc -jreLoc %JAVA_HOME% -ignoreSysPrereqs -force -novalidation ORACLE_HOME=%ORACLE_HOME%
+#    && DEL /Q C:\u01\%FMW_JAR% C:\u01\%FMW_PKG% C:\u01\install.file && `
+#    RD /S /Q C:\u01\oracle\cfgtoollogs
 
 # Final image stage
-FROM dockeronwindows/ser-java0:ananth
-USER ContainerUser
+# FROM dockeronwindows/ser-java0:ananth
 
 ENV ORACLE_HOME=C:\u01\oracle `
-    # USER_MEM_ARGS="-Djava.security.egd=file:\dev\.\urandom" `
     SCRIPT_FILE=C:\u01\oracle\createAndStartEmptyDomain.bat `
     HEALTH_SCRIPT_FILE=C:\u01\oracle\get_healthcheck_url.bat
 
@@ -94,30 +88,16 @@ ENV DOMAIN_NAME="${DOMAIN_NAME:-base_domain}" `
 # Setup filesystem and oracle user
 # Adjust file permissions, go to \u01 as user 'oracle' to proceed with WLS installation
 # ------------------------------------------------------------
-RUN mkdir  C:\u01\oracle
-# RUN icacls "C:\u01\oracle" /grant:r ContainerUser:(OI)(CI)F /T
-# ENV PATH=%PATH%;%JAVA_HOME%\bin;C:\u01\oracle\oracle_common\common\bin;C:\u01\oracle\wlserver\common\bin
-USER ContainerAdministrator
-RUN setx /M PATH %JAVA_HOME%\bin;C:\u01\oracle\oracle_common\common\bin;C:\u01\oracle\wlserver\common\bin;%PATH%
-# USER ContainerUser
-# && `
-#    chmod 775 \u01 && `
-#    useradd -b \u01 -d \u01\oracle -m -s \bin\bash oracle && `
-#    chown oracle:root \u01
+# RUN mkdir  C:\u01\oracle
 
-COPY --from=builder C:\u01 C:\u01
+# COPY --from=builder C:\u01 C:\u01
 
 # Copy scripts
 #-------------
-COPY container-scripts\createAndStartEmptyDomain.bat container-scripts\create-wls-domain.py container-scripts\get_healthcheck_url.bat \u01\oracle\
+COPY container-scripts\createAndStartEmptyDomain.bat container-scripts\create-wls-domain.py container-scripts\get_healthcheck_url.bat C:\u01\oracle\
 
-# RUN chmod +xr $SCRIPT_FILE $HEALTH_SCRIPT_FILE && `
-#    chown oracle:root $SCRIPT_FILE \u01\oracle\create-wls-domain.py $HEALTH_SCRIPT_FILE
-# RUN icacls "C:\u01\oracle" /grant:r ContainerUser:(OI)(CI)F /T
-#USER ContainerUser
-
-HEALTHCHECK --start-period=10s --timeout=30s --retries=3  CMD curl -k -s --fail `$HEALTH_SCRIPT_FILE` || exit 1
-WORKDIR ${ORACLE_HOME}
+# HEALTHCHECK --start-period=10s --timeout=30s --retries=3  CMD curl -k -s --fail "C:\u01\oracle\get_healthcheck_url.bat" || exit 1
+# WORKDIR C:\u01\oracle
 
 # Define default command to start script.
-CMD ["C:\u01\oracle\createAndStartEmptyDomain.bat"]
+CMD "C:\u01\oracle\createAndStartEmptyDomain.bat"
